version: '3'
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=visitors
    ports:
      - '5432:5432'
  app:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/visitors
    restart: on-failure
    volumes:
      - ./:/workspace:z
    ports:
      - '3000:3000'
